### ISSUE TITLE
Compile error LUA_GLOBALSINDEX

### ISSUE THREAD

**Issue by severach** [gmsoft-tuxicoman/pom-ng#12]
```addon.c: In function 'addon_lua_register':
addon.c:228:18: error: 'LUA_GLOBALSINDEX' undeclared (first use in this function)
  lua_setfield(L, LUA_GLOBALSINDEX, "POMLOG_ERR");
```

[Arch Package](https://aur.archlinux.org/packages/pom-ng-git/)
[More info](http://stackoverflow.com/questions/10087226/lua-5-2-lua-globalsindex-alternative)

**Comment by gmsoft-tuxicoman** [comment]
I merged a pull request for lua 5.2 support. This should fix the problem.
