### ISSUE TITLE
Docsis packet capture issue with WinTV HVR930c

### ISSUE THREAD

**Issue by jekkos** [gmsoft-tuxicoman/pom-ng#8]
Hey there,

First I'd like to confirm that the WinTV HVR-930C works with pom-ng. This tuner has the xc5000 inside and with a timeout of 12s and frontend reinitiliazition I seem to be able to scan the docsis spectrum.
Howeve when a stream is encountered the packet capture fails prematurely. Any idea what the issue might be here? Thanks.

 ```
input_docsis: DOCSIS 3 stream found. Switch this input to mode docsis3 to capture on multiple cards
input_docsis: Found DOCSIS 3 frequency 402000000Hz (256QAM), primary capable
input_docsis: Found DOCSIS 3 frequency 410000000Hz (256QAM), primary capable
input_docsis: Found DOCSIS 3 frequency 418000000Hz (256QAM), primary capable
input_docsis: Found DOCSIS 3 frequency 426000000Hz (256QAM), primary capable
input_docsis: Found DOCSIS 3 frequency 434000000Hz (256QAM), primary capable
input_docsis: Found DOCSIS 3 frequency 442000000Hz (256QAM), primary capable
input_docsis: Found DOCSIS 3 frequency 450000000Hz (256QAM), primary capable
input_docsis: Found DOCSIS 3 frequency 458000000Hz (256QAM), primary capable
 
input_docsis: Total : DOCSIS 2545 packets, 0 (0.0%) invalid checksum | MPEG packet read 7902, missed 0 (0.0%), erroneous 0 (0.0%), invalid 0 (0.0%), total errors 0 (0.0%)
```

**Comment by gmsoft-tuxicoman** [comment]
Hi,

Sorry for the delay.

This output seems to come from packet-o-matic, not pom-ng.

Can you please try with pom-ng ?
See here for pom-ng's instructions :  http://wiki.packet-o-matic.org/pom-ng/docsis/docsis
Let me know if it's unclear.

Guy
