### ISSUE TITLE
Issue setting tuning parameters dvb_c input

### ISSUE THREAD

**Issue by jekkos** [gmsoft-tuxicoman/pom-ng#9]
When setting the tuning parameters for dvb_c input I get the following response from the dvbc driver

input_dvb: Error while setting tuning parameters : Invalid argument

Any idea why this might be? I tested on different machines with Ubuntu 10.10 and 12.04 and kernels 3.3.7 and 3.8, but same error there. 

For symbol rate I found 6875 
Frequency (322Mhz), so 322000000
Tuning timeout 10

data as found on http://dvblogic.com/wiki/index.php/Fast_channel_search_parameters#Belgium

Do I have all units right here or is there any value obviously wrong?

thanks

**Comment by jekkos** [comment]
Error occurs in src/modules/input/input_dvb.c:878
Looks like some kind of driver compatibility issue?

**Comment by gmsoft-tuxicoman** [comment]
Have you tried with 6875000 as a symbol rate ?

Moreover, if you are trying to find docsis stream, please try the input docsis_scan. See here for more details : http://wiki.packet-o-matic.org/pom-ng/docsis/docsis

**Comment by jekkos** [comment]
No it's not an dvb-c stream I think. If found that my setop box is fetching a MHP update with tuner freq set to 322Mhz, while this frequency is not showing up in the docsis scan. Just wanted to have a look whether there's anything visible on pom-ng during this process.

**Comment by jekkos** [comment]
Ok thanks the input is started now, looks like the symbol rate dimension was wrong indeed. Does pom-ng filter out packets that it can't reconstruct automatically? Im using just a single tuner now.

**Comment by gmsoft-tuxicoman** [comment]
Yep by default split traffic is filtered by the docsis module : 
http://wiki.packet-o-matic.org/pom-ng/proto/docsis

If it's a different protocol like mpeg MPE, it's probably not splitted on multiple freqs.
